# Generated by Django 4.0.4 on 2023-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('topskills', models.CharField(blank=True, max_length=2000, null=True)),
                ('skills', models.CharField(blank=True, max_length=2000, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
